name: github-pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  debug-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: debug-linux-x86_64
        run: |
          sudo apt-get update && sudo apt-get install -y libglu1-mesa-dev freeglut3-dev mesa-common-dev libjack-jackd2-dev
          sudo usermod -a -G audio $USER
          ./build.sh -DCMAKE_BUILD_TYPE=Debug
          rm torus
          mkdir -p torus/torus/
          cp -r build/torus torus/torus/
          cp LICENSE* torus/torus/
          chmod 755 torus/torus/torus

      - name: torus-debug-linux-x86_64
        uses: actions/upload-artifact@v2
        with:
          name: torus-debug-linux-x86_64
          path: |
            torus

  release-linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: release-linux-x86_64
        run: |
          sudo apt-get update && sudo apt-get install -y libglu1-mesa-dev freeglut3-dev mesa-common-dev libjack-jackd2-dev
          sudo usermod -a -G audio $USER
          ./build.sh -DCMAKE_BUILD_TYPE=Release
          rm torus
          mkdir -p torus/torus/
          cp -r build/torus torus/torus/
          cp LICENSE* torus/torus/
          chmod 755 torus/torus/torus

      - name: torus-release-linux-x86_64
        uses: actions/upload-artifact@v2
        with:
          name: torus-release-linux-x86_64
          path: |
            torus

  release-windows-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: release-windows-x86_64
        run: |
          sudo apt-get update && sudo apt-get install -y libglu1-mesa-dev freeglut3-dev mesa-common-dev mingw-w64 libjack-jackd2-dev
          sudo usermod -a -G audio $USER
          ./build-mingw.sh -DCMAKE_BUILD_TYPE=Release
          mkdir torus-root/
          mv torus/ torus-root/torus/
          mv torus-root/ torus/

      - name: torus-release-windows-x86_64
        uses: actions/upload-artifact@v2
        with:
          name: torus-release-windows-x86_64
          path: |
            torus
